### ISSUE TITLE
Predictions and buses

### ISSUE THREAD

**Issue by Friss** [abetusk/bostontraintrack#2]
I've been hacking around your project this week and have extended it to include the predictions of when it will arrive and the destination of each train. 

I'm also working on having the buses tracked on this as well. (I have it working but its crazy the amount of busses so I have them hidden by default.) I'm also working on getting the predictions for buses working as well but its a bit harder since the predictions are stop based more than bus based like the trains. 

Along the way I've been refactoring a lot of your code and such as well as splitting the repo into the server and the web client separately to easily deploy them on my server. 

https://github.com/Friss/BostonTransitServer
https://github.com/Friss/BostonTransitWeb

I'm not sure of how you wish to further develop the project but you can take a look at how I handle the train predictions and put that into this or I can submit a pull request with the changes. 

Here is the link to my version http://bostontransit.justdev.in/ 

Let me know what you think. Definitely believe this to be an interesting project and looking forward to continuing developing it over time.

**Comment by abetusk** [comment]
I would ask that if you want to merge back into bostontraintrack, that you
- make popups persistent, so they don't just popup on mouseover
- allow only 1 at a time
- move with the marker as it updates
- position them so they don't get in the way of the marker.

Putting arrival times is a very good improvement, but getting the little details right is always the tedious part.  Obviously no pressure as you can do what you like in your own fork and it's something I might get to later.

Rather than overloading this issue, I've opened some other issues that collect my thoughts on some possible improvements that you mention above:
- [Bus markers and routes](https://github.com/abetusk/bostontraintrack/issues/4)
- [Annotate stops with next arrival times](https://github.com/abetusk/bostontraintrack/issues/5)
- [Feedback widget or form on main page](https://github.com/abetusk/bostontraintrack/issues/6)

**Comment by abetusk** [comment]
Ok, I just went ahead and added most bus functionality, including making a bunch of icons for the different routes.  I made a separate bus server that listens on port 8182 to service those requests and added a button to toggle bus display.  The code is a bit messy as I decided to split most of the functionality into separate functions (which has the unfortunate effect of some code duplication).

Though there are a lot of buses, the fact that they're white and pretty transparent helps with the clutter (imo), so it seems pretty reasonable.

There is still the issue of stop prediction and popup messages to take care.  I'm going to close this issue.  If you'd like the rest of the functionality that you mentioned above, maybe it's best to open a separate issue per feature request.

Thanks for the links, it helped a lot to use your code as a reference for the extra functionality.
